### PR TITLE
xWebAdministration: Updated pipeline files to support change of master to main

### LINKED ISSUE #591: xWebAdministration: Rename master branch to main
As per [this statement](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

Follow this guide https://dsccommunity.org/blog/convert-master-to-main/

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Renamed `master` branch to `main` ([issue #591](https://github.com/PowerShell/xWebAdministration/issues/591)).
- The pipeline will now updaste the module manifest property `DscResourcesToExport`
  automatically.
- Only run the CI/CD pipeline on branch _main_ when there are changes to files
  inside the `source` folder.

#### This Pull Request (PR) fixes the following issues

- Fixes #591

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/592)

### CODE REVIEW

**Review by regedit32 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/592)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @johlju and @PlagueHO)

___
*[CHANGELOG.md, line 13 at r1](https://reviewable.io/reviews/dsccommunity/xwebadministration/592#-MQPrlor59PLV4tBFiZx:-MQPrlor59PLV4tBFiZy:bmyoaz5) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/6e08bc96342b9166f1dde947b0ad9465ae821804/CHANGELOG.md#L13)):*
> ```
> updaste
> ```
small typo....`update`

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/592)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @PlagueHO and @regedit32)

___
*[CHANGELOG.md, line 13 at r1](https://reviewable.io/reviews/dsccommunity/xwebadministration/592#-MQPrlor59PLV4tBFiZx:-MQQrIqa5Lu_pViTcuuX:b-896fix) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/6e08bc96342b9166f1dde947b0ad9465ae821804/CHANGELOG.md#L13)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
> updaste
> ```
small typo....`update`
</blockquote></details>

Done.

**Comment by johlju** [comment]
@regedit32 thanks for the review! 🙂 Fixed the review comment, good catch. 🙂

**Comment by johlju** [comment]
I merge this, so I can continue with the next steps.

**Pull request merged**
