### PR TITLE
xWebsite: Compare LogTruncateSize parameter correctly

### LINKED ISSUE #380: xWebsite: LogTruncateSize is not a property of (Get-Website).LogFile
Setting LogTruncateSize in xWebsite always fails Test-TargetResource because it compares $LogTruncateSize to (Get-Website).logFile.LogTruncatesize. 

The property is TruncateSize, not LogTruncateSize so Test-TargetResource always fails.

https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1062

### PR DESCRIPTION
**Pull request by nickgw**
xWebsite attempts to compare the passed `$LogTruncateSize` to (essentially) `(Get-Website -Name $name).logFile.LogTruncateSize` except, the parameter is `truncatesize`. This causes the comparison to always fail.

Fixes #380

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/381)

### CODE REVIEW

**Comment by johlju** [comment]
Could you please look why the tests are failing?

**Comment by nickgw** [comment]
Looks like there was something else going on at the same time: 
`The process cannot access the file 'C:\windows\system32\inetsrv\config\applicationHost.config' because it is being used by another process.`

**Comment by johlju** [comment]
Ah some timing issue, think I’ve seen that before. Closing the PR and directly reopening the existing PR again will kick off the tests again.

**Comment by nickgw** [comment]
I believe it is because the unit tests always check for failure scenarios but never successful scenarios. If I'm reading the tests right:

[L269](https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/Unit/MSFT_xWebsite.Tests.ps1#L269) test that they match, calling the right parameter names (`LogTruncateSize` for passed parameter and `truncatesize` for website parameter), 

[L681](https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/Unit/MSFT_xWebsite.Tests.ps1#L681) test for failure when the `truncatesize` is different, and 

[L777](https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/Unit/MSFT_xWebsite.Tests.ps1#L777) tests for failure when `LogTruncateSize` is larger than `truncatesize`. 

[L1524](https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/Unit/MSFT_xWebsite.Tests.ps1#L1524) isn't testing for comparison between the two (though I'm not the best with Pester). 

If there was a test that the given `LogTruncateSize`  matches `truncatesize` looking for a `True`, this would have been caught.

**Comment by johlju** [comment]
When looking at the lines you provided, it seems that the unit test was mocking this correctly, so the unit tests always tests the correct property.

https://github.com/PowerShell/xWebAdministration/blob/a07d02c295f49efd5a608f0915a7dfdf19d6da2b/Tests/Unit/MSFT_xWebsite.Tests.ps1#L102-L122

https://github.com/PowerShell/xWebAdministration/blob/a07d02c295f49efd5a608f0915a7dfdf19d6da2b/Tests/Unit/MSFT_xWebsite.Tests.ps1#L665

We should test this property in the integration test, where it would have been caught, since there `Get-WebSite` is not mocked.

**Comment by johlju** [comment]
No I take that back. This should have been caught in the unit tests. Something is off with the unit test. It mocked the return value as, for example, `truncateSize      = '1048576' `, and that could never have been returned, since when it previously returned `LogTruncateSize` it would have returned a `$null` value. 🤔 

Using the parameters you used to hit this bug, could you with those create a new unit test for each function, that catch this bug (and with you fix the tests passes)?

**Pull request closed without merging**
